services:
  web:
    build: ./pythonCrud
    image: python-crud:latest
    container_name: python-crud
    restart: always
    command: >
        sh -c "pip install requests==2.27.1 Django==4.0.5 django-cors-headers==3.13.0 djangorestframework==3.13.1 djongo==1.3.5 pymongo==3.12.3 python-dotenv==0.20.0 dnspython==2.2.1 &&
                python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes:
      - ${PWD}/PYTHONCRUD:/pythonCrud
    ports:
      - 8000:8000
