# Generated by Django 4.0.5 on 2022-06-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=300)),
                ('ContactNumber', models.CharField(max_length=15)),
                ('Adress', models.TextField()),
                ('Profession', models.CharField(max_length=50)),
                ('ResumeFileName', models.CharField(max_length=500)),
            ],
        ),
    ]
